name: flutter drive
on: pull_request
jobs:
  drive:
    strategy:
      matrix:
        device:
        - "iPhone 8 (13.7)"
      fail-fast: false
    runs-on: macOS-latest
    steps:
    - name: "List all simulators"
      run: "xcrun instruments -s"
    - name: "Start Simulator"
      run: |
        UDID=$(
          xcrun instruments -s |
          awk \
            -F ' *[][]' \
            -v 'device=${{ matrix.device }}' \
            '$1 == device { print $2 }'
        )
        xcrun simctl boot "${UDID:?No Simulator with this name found}"
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
        flutter-version: '1.21.0-7.0.pre'
    - name: "Run Flutter Driver tests"
      run: "flutter drive --target=test/app.dart"
